services:
  api:
    build: .
    ports:
    - "8000:8080"
    volumes:
    - ./src:/app/scr
    - ./tests:/app/tests
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_started
        restart: true
  db:
    image: "postgres:alpine"
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
